#!/bin/bash
# ===========================================
# Composition Assistant - Environment Setup
# ===========================================
# This script creates the .env file with your configuration
# Run: ./scripts/setup-env.sh

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  🎵 Composition Assistant - Environment Setup${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
    echo -e "${YELLOW}⚠ .env file already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Keeping existing .env file${NC}"
        exit 0
    fi
fi

echo ""
echo -e "${CYAN}Ollama Configuration${NC}"
echo -e "Make sure Ollama is running locally or provide cloud URL"
echo ""

read -p "Enter Ollama Host URL [http://host.docker.internal:11434]: " OLLAMA_HOST
OLLAMA_HOST=${OLLAMA_HOST:-http://host.docker.internal:11434}

read -p "Enter Ollama Model [qwen2.5:7b]: " OLLAMA_MODEL
OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5:7b}

echo ""
echo -e "${CYAN}Server Configuration${NC}"
echo ""

read -p "Enter API Port [8000]: " API_PORT
API_PORT=${API_PORT:-8000}

read -p "Enter UI Port [3000]: " UI_PORT
UI_PORT=${UI_PORT:-3000}

read -p "Enter Log Level [INFO]: " LOG_LEVEL
LOG_LEVEL=${LOG_LEVEL:-INFO}

# Create .env file
cat > .env << EOF
# ===========================================
# Composition Assistant Configuration
# ===========================================
# Generated by setup-env.sh on $(date)

# ---- Ollama Configuration ----
OLLAMA_HOST=${OLLAMA_HOST}
OLLAMA_MODEL=${OLLAMA_MODEL}

# ---- Audio Processing ----
SOUNDFONT_PATH=/app/FluidR3_GM/FluidR3_GM.sf2

# ---- Server Configuration ----
API_HOST=0.0.0.0
API_PORT=${API_PORT}
UI_PORT=${UI_PORT}

# ---- Logging ----
LOG_LEVEL=${LOG_LEVEL}
PYTHONUNBUFFERED=1
EOF

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ .env file created successfully!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}Configuration Summary:${NC}"
echo "  Ollama Host:  ${OLLAMA_HOST}"
echo "  Ollama Model: ${OLLAMA_MODEL}"
echo "  API Port:     ${API_PORT}"
echo "  UI Port:      ${UI_PORT}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "  1. make build    (build Docker images)"
echo "  2. make up       (start containers)"
echo "  3. Open http://localhost:${UI_PORT} for UI"
echo ""
