#!/bin/bash
# ===========================================
# Composition Assistant - Personal Setup
# ===========================================
# This script loads your personal configuration.
# Edit the values below with your settings.
# Run: ./scripts/setup-personal.sh

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  🎵 Loading Personal Configuration${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ============================================
# EDIT THESE VALUES WITH YOUR CONFIGURATION
# ============================================

# Ollama Configuration
OLLAMA_HOST="http://host.docker.internal:11434"
OLLAMA_MODEL="qwen2.5:7b"

# Server Ports
API_PORT="8000"
UI_PORT="3000"

# Log Level (DEBUG, INFO, WARNING, ERROR)
LOG_LEVEL="INFO"

# ============================================
# DO NOT EDIT BELOW THIS LINE
# ============================================

cat > .env << EOF
# ===========================================
# Composition Assistant Configuration
# ===========================================
# Generated by setup-personal.sh on $(date)

# ---- Ollama Configuration ----
OLLAMA_HOST=${OLLAMA_HOST}
OLLAMA_MODEL=${OLLAMA_MODEL}

# ---- Audio Processing ----
SOUNDFONT_PATH=/app/FluidR3_GM/FluidR3_GM.sf2

# ---- Server Configuration ----
API_HOST=0.0.0.0
API_PORT=${API_PORT}
UI_PORT=${UI_PORT}

# ---- Logging ----
LOG_LEVEL=${LOG_LEVEL}
PYTHONUNBUFFERED=1
EOF

echo -e "${GREEN}✓ .env file created from personal configuration${NC}"
echo ""
echo "Configuration:"
echo "  Ollama Host:  ${OLLAMA_HOST}"
echo "  Ollama Model: ${OLLAMA_MODEL}"
echo "  API Port:     ${API_PORT}"
echo "  UI Port:      ${UI_PORT}"
echo ""
